Database 201-721/Controllers/CourseController.cs
using Database_201_721.Models;
using Database_201_721.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Database_201_721.Controllers
{
    public class CourseController : Controller
    {

        private readonly ApplicationContext _applicationContext;

        public CourseController(ApplicationContext applicationContext)
        {
            _applicationContext = applicationContext;
        }

        [Authorize(Roles = "admin")]
        public IActionResult CourseList()
        {
            var courseList = _applicationContext.Courses.ToList();
            return View(courseList);
        }


        [Authorize(Roles = "admin")]
        public IActionResult AddCourse()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult AddCourse(CourseViewModel courseViewModel)
        {
            if (courseViewModel != null)
            {
                Course newCourse = new Course();
                newCourse.Id = courseViewModel.Id;
                newCourse.CourseName = courseViewModel.CourseName;

                _applicationContext.Courses.Add(newCourse);
            }
            _applicationContext.SaveChanges();
            return RedirectToAction("CourseList");
        }



        [Authorize(Roles = "admin")]
        public IActionResult Edit() => View();
        [HttpPost]

        [Authorize(Roles = "admin")]
        public IActionResult Edit(Course course)
        {
            _applicationContext.Courses.Update(course);

            _applicationContext.SaveChanges();

            return RedirectToAction("CourseList");
        }


        public IActionResult Delete(int id)
        {
            Course forDelete = _applicationContext.Courses.Find(id);
            
            if (forDelete != null)
            {
                _applicationContext.Courses.Remove(forDelete);
            }
            
            _applicationContext.SaveChanges();

            return RedirectToAction("CourseList");
        }

    }
}

Database 201-721/Controllers/RolesController.cs
using Database_201_721.Models;
using Database_201_721.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Database_201_721.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        

        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {

            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {

                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {

            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {

                var userRoles = await _userManager.GetRolesAsync(user);

                var allRoles = _roleManager.Roles.ToList();

                var addedRoles = roles.Except(userRoles);

                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Database 201-721/Controllers/UserManageController.cs
using Database_201_721.Models;
using Database_201_721.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Database_201_721.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserManageController : Controller
    {
        UserManager<User> _userManager;
        private readonly ApplicationContext _applicationContext;
        public UserManageController(UserManager<User> userManager, ApplicationContext applicationContext)
        {
            _userManager = userManager;
            _applicationContext = applicationContext;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { 
                    Email = model.Email, 
                    UserName = model.Email, 
                    Year = model.Year, 
                    FirstName = model.FirstName, 
                    LastName = model.LastName,
                };

                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var allGroup = _applicationContext.Groups.ToList();
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Year = user.Year, Groups= allGroup };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.FirstName = model.FirstName;
                    user.LastName = model.LastName;
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Year = model.Year;


                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> AddOrEditGroup(string id)
        {
            var allGroup = _applicationContext.Groups.ToList();
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Groups = allGroup };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrEditGroup(EditUserViewModel model)
        {
            User user = await _userManager.FindByIdAsync(model.Id);
            if (user != null)
            {
                var group = _applicationContext.Groups.FirstOrDefault(x => x.Id == model.GroupId);

                user.Group = group;
                if (group.Users == null)
                {
                    List<User> users = new List<User>();
                    users.Add(user);
                    group.Users = users;
                }
                else
                {
                    group.Users.Add(user);
                }

                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else 
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }


        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }



        public async Task<IActionResult> ChangeRequeist(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            return View(user);
        }
        [HttpPost]
        public async Task<ActionResult> ChangeRequeist(User userFromView)
        {
            var user = await _userManager.FindByIdAsync(userFromView.Id);

            if (user.ChangeRequestYear != 0)
            {
                user.Year = (int)user.ChangeRequestYear;
                user.ChangeRequestYear = null;
            }
            if (user != null)
            {
                _applicationContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Database 201-721/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Database_201_721</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Database_201_721.styles.css" asp-append-version="true" />
</head>


<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Database_201_721</a>
                }
                @if (!User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login">Database_201_721</a>
                }

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                {
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item"> 
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserManage" asp-action="Index">Пользователи</a>
                        </li>
                        <li class="nav-item"> 
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                        </li>
                        <li class="nav-item"> 
                            <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="GroupList">Группы</a>
                        </li>            
                        <li class="nav-item"> 
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="CourseList">Курсы</a>
                        </li>  
                    </ul>

                    <form class="nav-item" method="post" asp-controller="Account" asp-action="Logout">
                                 <input type="submit" value="Выход" />
                    </form>
                }   
  
                    
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">

        <div class="row">
            @if (User.Identity.IsAuthenticated && User.IsInRole("student"))
            {
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                    <div class="position-sticky pt-3">

                        <ul class="nav flex-column">

                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller = "User" asp-action = "AboutMe" asp-route-email = "@User.Identity.Name">
                               Личный кабинет 
                            </a>
                          </li>

                           <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller = "User" asp-action = "ChangeInformationAboutMe" asp-route-email = "@User.Identity.Name">
                               Изменить информацию о себе 
                            </a>
                          </li>

                           <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller = "User" asp-action = "StudentsInGroup" asp-route-email = "@User.Identity.Name">
                               Группа
                            </a>
                          </li>

                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller = "User" asp-action = "CourseList" asp-route-email = "@User.Identity.Name">
                               Курсы
                            </a>
                          </li>

                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller = "User" asp-action = "EmptyBlank">
                               Бланки заявлений
                            </a>
                          </li>
                          <li class="mt-5 nav-item">
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                   <input class=" nav-link active" type="submit" value="Выход" />
                            </form>
                          </li>
                        </ul>

                    </div>
                </nav>
            }
          <main class="ms-sm-auto col-lg-10 px-md-4">

              <div class="chartjs-size-monitor">
                  <div class="chartjs-size-monitor-expand">
                      <div class=""></div>
                  </div>
                  <div class="chartjs-size-monitor-shrink">
                       <div class=""></div>
                  </div>
               </div>

            <div>
              @RenderBody()
            </div>

          </main>

        </div>

    </div>




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>